version: "3"
services:
  client:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app
    networks:
      - backend
  server:
    build:
      context: ./backend
    volumes:
      - ./backend/:/app
    networks:
      - backend
    depends_on:
      - mongo

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: abaotest
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
