version: "3"
services:
  client:                 
    build:
      context: ./frontend 
    volumes:
      - ./frontend/:/app      
      - /app/node_modules  
    networks:
      - backend           
  server:                          
    build:
      context: ./backend
    volumes:
      - ./backend/:/app      
      - /app/node_modules      
    networks:
      - backend  
      
  nginx:
    restart: always
    build:
      context: ./nginx 
    ports:
      - '80:80' 
    networks:
      - backend
    
networks: 
  backend:
    driver: bridge

volumes:
  data:
    driver: local  
